import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common'; import { InjectRepository } from '@nestjs/typeorm'; import { In, Repository } from 'typeorm'; import { Cita } from './entities/cita.entity'; import { Cliente } from '../clientes/entities/cliente.entity'; import { Barbero } from '../barberos/entities/barbero.entity'; import { Servicio } from '../servicios/entities/servicio.entity'; import { DetalleCita } from './entities/detalle-cita.entity'; import { CreateCitaDto } from './dto/create-cita.dto'; import { UpdateCitaDto } from './dto/update-cita.dto'; import { EstadoCitaDto } from './dto/estado-cita.dto'; import { ReprogramarCitaDto } from './dto/reprogramar-cita.dto'; import { EstadoCita } from '../common/enums/estado-cita.enum'; import { RolUsuario } from '../common/enums/roles.enum';
@Injectable() export class CitasService {
  constructor(@InjectRepository(Cita) private readonly repo:Repository<Cita>,@InjectRepository(Cliente) private readonly clientes:Repository<Cliente>,@InjectRepository(Barbero) private readonly barberos:Repository<Barbero>,@InjectRepository(Servicio) private readonly servicios:Repository<Servicio>,@InjectRepository(DetalleCita) private readonly detalles:Repository<DetalleCita>){}
  private relations={cliente:{usuario:true},barbero:{usuario:true},detalles:{servicio:true},pago:true};
  findAll(){return this.repo.find({relations:this.relations,order:{fecha:'ASC',hora:'ASC'}});}
  async findOne(id:string){const x=await this.repo.findOne({where:{id},relations:this.relations});if(!x)throw new NotFoundException('Cita no encontrada.');return x;}
  private async assertAvailable(barberoId:string,fecha:string,hora:string,excludeId?:string){const qb=this.repo.createQueryBuilder('c').where('c.barbero_id = :barberoId',{barberoId}).andWhere('c.fecha = :fecha',{fecha}).andWhere('c.hora = :hora',{hora}).andWhere('c.estado <> :cancelada',{cancelada:EstadoCita.CANCELADA});if(excludeId)qb.andWhere('c.id <> :excludeId',{excludeId});if(await qb.getOne())throw new ConflictException('El barbero ya tiene una cita en esa fecha y hora.');}
  async create(dto:CreateCitaDto){const cliente=await this.clientes.findOne({where:{id:dto.clienteId}});if(!cliente)throw new NotFoundException('Cliente no encontrado.');const barbero=await this.barberos.findOne({where:{id:dto.barberoId}});if(!barbero||!barbero.disponible)throw new BadRequestException('El barbero no está disponible.');const servicios=await this.servicios.find({where:{id:In(dto.servicioIds)}});if(servicios.length!==dto.servicioIds.length||servicios.some(s=>!s.activo))throw new BadRequestException('Uno o más servicios no existen o están inactivos.');await this.assertAvailable(dto.barberoId,dto.fecha,dto.hora);const cita=this.repo.create({cliente,barbero,fecha:dto.fecha,hora:dto.hora,estado:EstadoCita.PROGRAMADA,observaciones:dto.observaciones,detalles:servicios.map(s=>this.detalles.create({servicio:s,precio:s.precio}))});const saved=await this.repo.save(cita);return this.findOne(saved.id);}
  async update(id:string,dto:UpdateCitaDto){const x=await this.findOne(id);if(x.estado===EstadoCita.CANCELADA||x.estado===EstadoCita.FINALIZADA)throw new BadRequestException('La cita no puede modificarse en su estado actual.');const barberoId=dto.barberoId??x.barbero.id;const fecha=dto.fecha??x.fecha;const hora=dto.hora??x.hora;await this.assertAvailable(barberoId,fecha,hora,id);if(dto.barberoId){const b=await this.barberos.findOne({where:{id:dto.barberoId}});if(!b)throw new NotFoundException('Barbero no encontrado.');x.barbero=b;}x.fecha=fecha;x.hora=hora;if(dto.observaciones!==undefined)x.observaciones=dto.observaciones;return this.repo.save(x);}
  async updateStatus(id:string,dto:EstadoCitaDto){const x=await this.findOne(id);x.estado=dto.estado;return this.repo.save(x);}
  async reprogramar(id:string,dto:ReprogramarCitaDto){return this.update(id,{fecha:dto.fecha,hora:dto.hora,barberoId:dto.barberoId});}
  async cancel(id:string){const x=await this.findOne(id);if(x.estado===EstadoCita.FINALIZADA)throw new BadRequestException('Una cita finalizada no puede cancelarse.');x.estado=EstadoCita.CANCELADA;return this.repo.save(x);}
  async byClient(clientId:string){return this.repo.find({where:{cliente:{id:clientId}},relations:this.relations,order:{fecha:'DESC',hora:'DESC'}});}
  async byBarber(barberId:string){return this.repo.find({where:{barbero:{id:barberId}},relations:this.relations,order:{fecha:'ASC',hora:'ASC'}});}
}
